### ISSUE TITLE
Add javascript/typescript Dockerfile template

### ISSUE THREAD

**Issue by FelipeMCassiano** [FelipeMCassiano/gorvus#2]
We currently lack a Dockerfile template for  projects in our repository. To facilitate the usage of Docker for javascript/typescript development and deployment, we should add a standardized Dockerfile template tailored for javascript/typescript applications

**Comment by notshwuy** [comment]
There are many JavaScript engines: Node, Bun, Deno... bundlers also adds up. 
I think it would be good to have `bun+tsx`/`node+tsx` or something like that in the template names.

**Comment by FelipeMCassiano** [comment]
> There are many JavaScript engines: Node, Bun, Deno... bundlers also adds up. I think it would be good to have `bun+tsx`/`node+tsx` or something like that in the template names.

Noted!
