### ISSUE TITLE
Add Docker Compose Generation Feature

### ISSUE THREAD

**Issue by FelipeMCassiano** [FelipeMCassiano/gorvus#3]
Currently, our project lacks a feature for generating docker-compose.yml files, which are essential for orchestrating multi-container Docker applications. To enhance the usability and convenience of our tool, we should implement a feature that allows users to generate docker-compose.yml files based on their project specifications.

**Comment by notshwuy** [comment]
Could you assign me on this? I want to build an incremental `docker-compose.yml` generator.

**Comment by FelipeMCassiano** [comment]
> Could you assign me on this? I want to build an incremental `docker-compose.yml` generator.

sure!
